echo "current user: $USER Login name: $LOGNAME"
echo "current shell: $SHELL"
echo "home directory: $HOME"
echo "os type: $uname -o"
echo "pwd: $PWD"
echo "currently logged users: $(who | wc -l)"
echo "pwd: $PATH"
